---
- name: Configure SSH keys
  hosts: localhost
  tasks:
    # Find the private keys in the Vagrant folder
    - command: find /home/vagrant/sync/.vagrant/machines -name private_key
      register: private_keys
      changed_when: no

    # Create symlinks for the private keys and set correct permissions (0600)
    - file:
        src: "{{ item }}"
        dest: "/home/vagrant/.ssh/{{ item | regex_replace('^.*/machines/([^/]*)/.*', '\\1') }}.key"
        state: link
        mode: '0600'
        owner: vagrant
        group: vagrant
      with_items: "{{ private_keys.stdout_lines }}"

- name: Bootstrap Admin Host
  hosts: admin1
  tasks:
    - include: tasks/install_bootstrap_origin.yaml

- name: Add EPEL repository and install dependencies for CentOS 9 Stream
  hosts: all
  tasks:
    - name: Enable EPEL repository for CentOS 9
      yum:
        name: epel-release
        state: present

    - name: Install necessary dependencies for OpenShift on CentOS 9 Stream
      yum:
        name:
          - wget
          - docker
          - git
          - ansible
        state: present

- name: Install OpenShift 4.17 Client (oc)
  hosts: all
  tasks:
    - name: Download OpenShift CLI
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.17/openshift-client-linux.tar.gz
        dest: /tmp/openshift-client-linux.tar.gz

    - name: Extract OpenShift CLI
      unarchive:
        src: /tmp/openshift-client-linux.tar.gz
        dest: /usr/local/bin
        remote_src: yes

    - name: Ensure OpenShift CLI is executable
      file:
        path: /usr/local/bin/oc
        mode: '0755'

- name: Install OpenShift 4.17 Installer (optional)
  hosts: all
  tasks:
    - name: Download OpenShift Installer
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.17/openshift-install-linux.tar.gz
        dest: /tmp/openshift-install-linux.tar.gz

    - name: Extract OpenShift Installer
      unarchive:
        src: /tmp/openshift-install-linux.tar.gz
        dest: /usr/local/bin
        remote_src: yes

    - name: Ensure OpenShift Installer is executable
      file:
        path: /usr/local/bin/openshift-install
        mode: '0755'
