---
- name: Configure ssh keys
  hosts: localhost
  tasks:
    # Find the private keys in the Vagrant folder
    - command: find /home/vagrant/sync/.vagrant/machines -name private_key
      register: private_keys
      changed_when: no

    # Create symlinks for the private keys and set correct permissions (0600)
    - file:
        src: "{{ item }}"
        dest: "/home/vagrant/.ssh/{{ item | regex_replace('^.*/machines/([^/]*)/.*', '\\1') }}.key"
        state: link
        mode: '0600'  # Fix permission issue for SSH private keys
        owner: vagrant
        group: vagrant
      with_items: "{{ private_keys.stdout_lines }}"

- name: Bootstrap Admin Host
  hosts: admin1
  tasks:
    - include: tasks/install_bootstrap_origin.yaml

- name: Add EPEL repository for CentOS 9 Stream
  hosts: all
  tasks:
    - name: Enable EPEL repository for CentOS 9
      yum:
        name: epel-release
        state: present

    - name: Install necessary dependencies for OpenShift on CentOS 9 Stream
      yum:
        name:
          - wget
          - docker
          - git
          - ansible
        state: present
