---
- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: present
    update_cache: yes

- name: Copy in dnsmasq config
  copy:
    src: openshift.conf
    dest: /etc/dnsmasq.d/openshift.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_dnsmasq

- name: Start service dnsmasq, if not started
  service:
    name: dnsmasq
    daemon_reload: yes
    state: started
    enabled: yes

- name: Configure NetworkManager DNS settings
  nmcli:
    conn_name: "System eth0"
    dns4: 127.0.0.1
    type: ethernet
    state: present
  when: '"127.0.0.1" not in ansible_dns.nameservers'
  notify:
    - restart_NetworkManager

